jiz/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	    # Examples:
        # url(r'^$', 'mysite.views.home', name='home'),
	    # url(r'^mysite/', include('mysite.foo.urls')),

        # Uncomment the admin/doc line below to enable admin documentation:
	    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

        # Uncomment the next line to enable the admin:
        url(r'^admin/', include(admin.site.urls)),
	    #url(r'^$', include('jizhang.urls', namespace="jizhang")),
	    url(r'', include('jizhang.urls', namespace = 'jizhang')),
					)

jizhang/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from jizhang import views

urlpatterns = patterns('',
        url(r'^$', views.home, name = 'home'),
		
        #url(r'^customers/(?P<cust_id>\d+)', views.Customers, name = 'Customers'),
        #url(r'^customers/*(?P<cust_id>\d*)/?$', views.Customers, name = 'Customers'),
        # * means >= 0
        # + means >= 1
        #url(r'^products/*(?P<prod_id>\d*)/?$', views.Products, name = 'Products'),
        #url(r'^orders/*(?P<order_id>\d*)/?$', views.Orders, name = 'Orders'),


        url(r'^customers/?$', views.CustomersHome, name = 'CustomersHome'),
        #url(r'^customers/(?P<cust_id>\d+)/?$', views.CustomerDetails, name = 'CustomerDetails'),
        #url(r'^customers/\d+/?$', views.CustomerDetails, name = 'CustomerDetails'),
        url(r'^customer/?$', views.CustomerDetails, name = 'CustomerDetails'),

        url(r'^products/?$', views.ProductsHome, name = 'ProductsHome'),
        url(r'^product/?$', views.ProductDetails, name = 'ProductDetails'),

        url(r'^orders/?$', views.OrdersHome, name = 'OrdersHome'),
        url(r'^order/?$', views.OrderDetails, name = 'OrderDetails'),
        
	url(r'^vendors/?$', views.VendorsHome, name = 'VendorsHome'),
	url(r'^vendor/?$', views.VendorDetails, name = 'VendorDetails'),
		       )

jizhang/models.py
# -*- coding: utf-8 -*-

# Create your models here.

from django.db import models


class Customers(models.Model):
    cust_id = models.IntegerField(max_length = 11, primary_key = True)
    cust_name = models.CharField(max_length = 200)
    cust_address = models.CharField(max_length = 200)
    cust_city = models.CharField(max_length = 30)
    cust_state = models.CharField(max_length = 20)
    cust_zip = models.SmallIntegerField(null = True)
    cust_country = models.CharField(max_length = 50, default = 'China')
    cust_mobile = models.CharField(max_length = 20)
    cust_phone = models.SmallIntegerField(null = True)
    cust_email = models.EmailField(max_length = 254, null = True)
    cust_taobaoid = models.CharField(max_length = 30)
    cust_baiduid = models.CharField(max_length = 30, null = True)

class Orders(models.Model):
    order_id = models.IntegerField(max_length = 11, primary_key = True)
    order_date = models.DateField()
    cust_id = models.ForeignKey(Customers, db_column = 'cust_id')
    order_status = models.IntegerField()
    order_url = models.URLField()

class Vendors(models.Model):
    vend_id = models.IntegerField(max_length = 11, primary_key = True)
    vend_name = models.CharField(max_length = 100, default = 'Self')
    vend_address = models.CharField(max_length = 200, null = True)
    vend_city =  models.CharField(max_length = 30, null = True)
    vend_state = models.CharField(max_length = 20, null = True)
    vend_zip = models.IntegerField(null = True)
    vend_country = models.CharField(max_length = 50, default = 'China')

class Products(models.Model):
    prod_id = models.IntegerField(max_length = 11, primary_key = True)
    vend_id = models.ForeignKey(Vendors, db_column = 'vend_id')
    prod_name = models.CharField(max_length = 100)
    prod_price_in = models.DecimalField(max_digits = 8, decimal_places = 2)
    prod_price_out = models.DecimalField(max_digits = 8, decimal_places = 2)
    prod_desc = models.CharField(max_length = 254, null = True)
    prod_total_amount = models.IntegerField(max_length = 11)
    prod_batch_id = models.IntegerField(max_length = 11)
    def __unicode__(self):
	return self.prod_id
    '''
    def inventory(self):
	total_out = 0
	for order in self.Orderitems_set.all():
	    total_out = total_out + order.quantity
	return self.prod_total_amount - total_out
    '''
class Orderitems(models.Model):
    #order_id = models.ForeignKey(Orders, primary_key = True)
    order_item = models.IntegerField(max_length = 11, primary_key = True)
    order_id = models.ForeignKey(Orders, db_column = 'order_id')
    #order_item = models.IntegerField(max_length = 11)
    #prod_id = models.CharField(max_length = 50)
    prod_id = models.ForeignKey(Products, db_column = 'prod_id')
    quantity = models.IntegerField(max_length = 11)
    item_price = models.DecimalField(max_digits = 8, decimal_places = 2)


class Productnotes(models.Model):
    note_id = models.IntegerField(max_length = 11, primary_key = True)
    prod_id = models.ForeignKey(Products, db_column = 'prod_id')
    note_date = models.DateField()
    note_text = models.CharField(max_length = 254, null = True)

jizhang/views.py
# -*- coding: utf-8 -*-

# Create your views here.
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import Http404
import datetime


from jizhang.models import Orders, Customers, Products, Vendors, Orderitems, Productnotes


def home(request):
    #return HttpResponse("Hello, welcome to Jiz.")
    return render(request, 'jizhang/home.html')

def CustomersHome(request):
    return render(request, 'jizhang/customershome.html')

def CustomerDetails(request):
#	return HttpResponse("You are viewing Customer %s's information." % cust_id)
    key1 = request.GET.get('cust_id', None)
    key2 = request.GET.get('cust_name', None)
    key3 = request.GET.get('taobaoid', None)
    key4 = request.GET.get('baiduid', None)
    if key1 is not None:
	#cust = get_object_or_404(Customers, pk = key1)
	#cust = get_object_or_404(Customers, cust_id = key1)
	
        # get_object_or_404 calls get(), get_list_or_404 calls filter()
        cust = get_list_or_404(Customers, pk = key1)
    elif key2 is not None:
	#cust = get_object_or_404(Customers, pk = pk2)
        cust = get_list_or_404(Customers, cust_name__regex = key2)
    elif key3 is not None:
        cust = get_list_or_404(Customers, cust_taobaoid__regex = key3)
    elif key4 is not None:
        cust = get_list_or_404(Customers, cust_baiduid__regex = key4)
    return render(request, "jizhang/customer.html", {'cust': cust})

def ProductsHome(request):
    return render(request, 'jizhang/productshome.html')

def ProductDetails(request):
    if request.GET.has_key('AllProducts'):
        prod = get_list_or_404(Products)
    else:
        key1 = request.GET.get('prod_id', None)
        key2 = request.GET.get('prod_name', None)
        key3 = request.GET.get('vend_name', None)
        if key1 is not None:
            prod = get_list_or_404(Products, pk = key1)
        elif key2 is not None:
            prod = get_list_or_404(Products, prod_name__regex = key2)
        elif key3 is not None:
            vend = get_list_or_404(Vendors, vend_name__regex = key3)
	    prod = []
	    for v in vend:
	        prod.extend(Vendors.objects.get(vend_id = v.vend_id).products_set.all())
	#prod = get_list_or_404(Products, vend_id = vend[0].vend_id)
        '''
        inventory = {} 
        for p in prod:
	    total_out = 0
	    for order in Products.objects.get(pk = p.prod_id).orderitems_set.all(): 
	    #for order in p.Orderitems_set.all(): 
	        total_out = total_out + order.quantity
	    inv = p.prod_total_amount - total_out
	    inventory[p.prod_id] = inv
        return render(request, "jizhang/product.html", 
	        {'prod': prod,
	         'inventory': inventory})
        '''
    inventory = []
    for p in prod:
        total_out = 0
        for order in Products.objects.get(pk = p.prod_id).orderitems_set.all():
            total_out = total_out + order.quantity
        inv = p.prod_total_amount - total_out
        inventory.append((p, inv))
    return render(request, "jizhang/product.html", {'inventory': inventory})

    #return HttpResponse("You are viewing Product %s's information." % prod_id)

def OrdersHome(request):
    try:
        orders = Orders.objects.all().order_by('-order_date')[:5]
    except Orders.DoesNotExist:
        raise Http404
    return render(request, 'jizhang/ordershome.html', {'orders': orders})

def OrderDetails(request):
    key1 = request.GET.get('order_id', None)
    if key1 is not None:
        orders = get_list_or_404(Orders, pk = key1)
        #orders = Orders.objects.get(pk = key1)
        #return render(request, 'jizhang/order.html', {'orders':orders})
    elif request.GET.has_key('OrdersInWeek'):
        date = datetime.date.today()
        start_week = date - datetime.timedelta(date.weekday())
        end_week = start_week + datetime.timedelta(7)
        try:
            orders = Orders.objects.filter(order_date__range = [start_week, end_week])
        except Orders.DoesNotExist:
            raise Http404
        #return render(request, "jizhang/order.html", {'orders': orders} )
    elif request.GET.has_key('OrdersInMonth'):
	#orders = Orders.objects.filter(order_date__month = datetime.date.today().month)
	orders = get_list_or_404(Orders, order_date__month = datetime.date.today().month)
        #return render(request, 'jizhang/order.html', {'orders':orders})
   
    # caculate total price for a specific order #
    orders_with_totalprice = []
    for ord in orders:
	price = 0
	for item in ord.orderitems_set.all():
	    price = price + item.quantity * item.item_price
	orders_with_totalprice.append([ord, price])
    return render(request, "jizhang/order.html", {'OrdersWithTotalPrice': orders_with_totalprice})

def VendorsHome(request):
    return render(request, 'jizhang/vendorshome.html')

def VendorDetails(request):
    key1 = request.GET.get('vend_id', None)
    key2 = request.GET.get('vend_name', None)
    if key1 is not None:
        vend = get_list_or_404(Vendors, pk = key1)
    elif key2 is not None:
	vend = get_list_or_404(Vendors, vend_name__regex = key2)
    return render(request, "jizhang/vendor.html", {'vend': vend})

jizhang/templates/jizhang/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Jiz">
    <meta name="author" content="felix23ma@gmail.com">
    {% load staticfiles %}
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Jiz - 淘宝记账</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.css" rel="stylesheet"> -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/sticky-footer-navbar.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>    <!-- new added -->
              <span class="icon-bar"></span>    <!-- new added -->
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                  <li><a href="{% url "jizhang:home" %}">主页</a></li>
                  <li><a href="{% url "jizhang:OrdersHome" %}">订单</a></li>
                  <li><a href="{% url "jizhang:ProductsHome" %}">产品</a></li>
                  <li><a href="{% url "jizhang:CustomersHome" %}">客户</a></li>
                  <li><a href="{% url "jizhang:VendorsHome" %}">供应商</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

      <!-- Begin page content -->
      <div class="container">
        <div class="page-header">
          <h1>Sticky footer with fixed navbar</h1>
        </div>
        <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added within <code>#wrap</code> with <code>padding-top: 60px;</code> on the <code>.container</code>.</p>
        <p>Back to <a href="../sticky-footer">the default sticky footer</a> minus the navbar.</p>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="pull-right text-muted"><a href="#">Back to top</a></p>
        <p class="text-muted">
          <a href="mailto:felix23ma@gmail.com"><i class="fa fa-envelope-o fa-lg"></i></a>
          <a href="http://weibo.com/u/2215539845" target="_blank"><i class="fa fa-weibo fa-lg"></i></a>
        </p>
        <!--
        <ul>
          <li><i class="fa fa-envelope-o">: </i><a href="mailto:felix23ma@gmail.com">felixma</a></li>
          <li><i class="fa fa-weibo"></i>: <a href="http://weibo.com/u/2215539845" target="_blank">@七里山塘边</a></li>
        </ul>
        -->
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>

jizhang/templates/jizhang/customer.html
{% extends 'details.html' %}

{% block page %}

{% if cust %}
<h5>客户数: {{ cust|length}}</h5>
{% endif %}

<div class="row">
  <div class="col-md-10">
    <table class="table table-bordered table-hover">
    <tr class="active">
        <th>客户ID</th>
        <th>姓名</th>
        <th>手机</th>
        <th>淘宝ID</th>
        <th>淘宝ID</th>
        <th>地址</th>
    </tr>
	{% comment %}
		cust is already a list, so cannot use below
		{% for c in cust.all %}
	{% endcomment %}
    {% for c in cust %}
    <tr>
        <td>{{ c.cust_id }}</td>
        <td>{{ c.cust_name }}</td>
        <td>{{ c.cust_mobile }}</td>
        <td>{{ c.cust_taobaoid }}</td>
        <td>{{ c.cust_baiduid }}</td>
	    <td>{{ c.cust_country }} {{ c.cust_state }} {{ c.cust_city }} {{ c.cust_address }}</td>
    {% empty %}
        <td> Sorry</td>
    </tr>
    {% endfor %}
  </table>
  </div>
</div>

<a href="{% url "jizhang:CustomersHome" %}">返回</a>

{% endblock page %}

jizhang/templates/jizhang/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Jiz">
    <meta name="author" content="felix23ma@gmail.com">
    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

    <title>Jiz - 淘宝记账</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="{% static "css/carousel.css" %}" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">  <!-- defined in carousel.css -->
      <div class="container">
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url "jizhang:home" %}">主页</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li><a href="{% url "jizhang:home" %}">主页</a></li>
                  <li><a href="{% url "jizhang:OrdersHome" %}">订单</a></li>
                  <li><a href="{% url "jizhang:ProductsHome" %}">产品</a></li>
                  <li><a href="{% url "jizhang:CustomersHome" %}">客户</a></li>
                  <li><a href="{% url "jizhang:VendorsHome" %}">生产商</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div> 


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
            <!--<img data-src="{% static "js/holder.js" %}/900x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">-->
            <img src="{% static "img/chiqingsi1.jpg" %}" alt="chiqingsi1">
          <div class="container">
            <div class="carousel-caption">
            <!--
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            -->
            </div>
          </div>
        </div>
        <div class="item">
            <img src="{% static "img/chiqingsi2.jpg" %}" alt="chiqingsi2">
          <div class="container">
            <div class="carousel-caption">
            <!--
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            -->
            </div>
          </div>
        </div>
        <div class="item">
            <img src="{% static "img/chiqingsi3.jpg" %}" alt="chiqingsi3">
          <div class="container">
            <div class="carousel-caption">
            <!--
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            -->
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-3">
            <a href="{% url 'jizhang:OrdersHome' %}">
                <img class="img-circle" src="{% static "img/fadai1_small.jpg" %}" alt="Generic placeholder image"></a>
            <h3 class="text-center"><a href="{% url 'jizhang:OrdersHome' %}">订单</a></h3>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-3 -->
        <div class="col-lg-3">
            <a href="{% url 'jizhang:ProductsHome' %}">
                <img class="img-circle" src="{% static "img/fadai3_small.jpg" %}"  alt="Generic placeholder image"></a>
            <h3 class="text-center"><a href="{% url 'jizhang:ProductsHome' %}">产品</a></h3>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-3 -->
        <div class="col-lg-3">
            <a href="{% url 'jizhang:CustomersHome' %}">
                <img class="img-circle" src="{% static "img/bu1_small.jpg" %}"  alt="Generic placeholder image"></a>
            <h3 class="text-center"><a href="{% url 'jizhang:CustomersHome' %}">客户</a></h3>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-3 -->
        <div class="col-lg-3">
            <a href="{% url 'jizhang:ProductsHome' %}">
                <img class="img-circle" src="{% static "img/bu3_small.jpg" %}"  alt="Generic placeholder image"></a>
            <h3 class="text-center"><a href="{% url 'jizhang:VendorsHome' %}">生产商</a></h3>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-3 -->
      </div><!-- /.row -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->



      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/holder.js" %}"></script>
  </body>
</html>

jizhang/templates/jizhang/order.html
{% extends 'details.html' %}

{% block page %}

{% if OrdersWithTotalPrice %}
<h5>订单数: {{ OrdersWithTotalPrice|length}}</h5>
{% endif %}

<div class="row">
  <div class="col-md-10">
    <table class="table table-bordered table-hover">
      <tr class="active">
        <th>订单ID</th>
        <th>下单日期</th>
        <th>状态</th>
        <th>客户</th>
        <th>订单URL</th>
        <th>产品</th>
        <th>数量</th>
        <th>单价</th>
        <th>总价</th>
    </tr>
    {% for order, price in OrdersWithTotalPrice %}
    <tr>
	<td rowspan={{ order.orderitems_set.all.count }}>{{ order.order_id }}</td>
	<td rowspan={{ order.orderitems_set.all.count }}>{{ order.order_date }}</td>
	<td rowspan={{ order.orderitems_set.all.count }}>{{ order.order_status }}</td>
	<td rowspan={{ order.orderitems_set.all.count }}><a href={% url 'jizhang:CustomerDetails' %}?cust_id={{ order.cust_id.cust_id }}>{{ order.cust_id.cust_name }}</td>
        <td rowspan={{ order.orderitems_set.all.count }}><a href={{ order.order_url }}>这里</td>
	{% for item in order.orderitems_set.all %}
	<td><a href="{% url 'jizhang:ProductDetails'%}?prod_id={{ item.prod_id }}">{{ item.prod_id.prod_name }}</td>
	<td>{{ item.quantity }}</td>
	<td>{{ item.item_price }}</td>
	<td>{{ price }}</td>
	</tr>
	<tr>
	{% endfor %}
    </tr>
    {% endfor %}
  </table>
 </div>
</div>

<a href="{% url "jizhang:OrdersHome" %}">返回</a>

{% endblock page %}

jizhang/templates/jizhang/product.html
{% extends 'details.html' %}

{% block page %}

{% if inventory %}
<h5>产品总数: {{ inventory|length}}</h5>
{% endif %}

<div class="row">
  <div class="col-md-10">
     <table class="table table-bordered table-hover"> 
       <tr class="active">
        <th>产品ID</th>
        <th>名称</th>
        <th>生产商</th>
        <th>进价</th>
        <th>出价</th>
        <th>进货总数</th>
        <th>库存</th>
        <th>批次</th>
        <th>描述</th>
       </tr>
       {% for prod,inv in inventory %}
       <tr>
        <td>{{ prod.prod_id }}</td>
        <td>{{ prod.prod_name }}</td>
	   <td><a href={% url 'jizhang:VendorDetails' %}?vend_id={{ prod.vend_id.vend_id }}>{{ prod.vend_id.vend_name }}</a></td>
        <td>{{ prod.prod_price_in }}</td>
        <td>{{ prod.prod_price_out }}</td>
        <td>{{ prod.prod_total_amount }}</td>
	   <td>{{ inv }}</td>
        <td>{{ prod.prod_batch_id }}</td>
        <td>{{ prod.prod_desc }}</td>
      {% empty %}
        <td> Sorry</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<a href="{% url "jizhang:ProductsHome" %}">返回</a>

{% endblock page %}